# Generated by Django 5.1.6 on 2025-03-05 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_productimage_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_feature',
            field=models.BooleanField(default=False),
        ),
    ]
