# Generated by Django 5.1.6 on 2025-05-27 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_featured',
            new_name='is_feature',
        ),
    ]
