# Generated by Django 5.1.6 on 2025-03-05 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_guestcart_guestcartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestcart',
            name='user_session_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='guestcart',
            name='session_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='guestcart',
            unique_together={('session_id', 'user_session_id')},
        ),
    ]
