# Generated by Django 5.1.6 on 2025-03-05 11:52

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_guestcart_user_session_id_alter_guestcart_session_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestcart',
            name='expires_at',
            field=models.DateTimeField(default=api.models.get_expiry_time),
        ),
        migrations.AlterField(
            model_name='guestcart',
            name='session_id',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='guestcart',
            name='user_session_id',
            field=models.CharField(default='legacy_session', help_text='Unique identifier for guest user session', max_length=100),
        ),
    ]
