# Generated by Django 5.1.6 on 2025-03-05 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_cartitem_unique_together_alter_cart_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='location_type',
            field=models.CharField(choices=[('CBD', 'Central Business District'), ('COMMERCIAL', 'Commercial Area'), ('GOVERNMENT', 'Government Area'), ('RESIDENTIAL', 'Residential Area'), ('INDUSTRIAL', 'Industrial Area'), ('SATELLITE_TOWN', 'Satellite Town'), ('SUBURBAN', 'Suburban Area'), ('RURAL', 'Rural Area')], default='CBD', help_text='Type of location', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='special_instructions',
            field=models.TextField(blank=True, help_text='Any special delivery instructions', null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_location',
            field=models.CharField(choices=[('KENCOM', 'Kencom'), ('KENYATTA_AVE', 'Kenyatta Avenue'), ('MOI_AVE', 'Moi Avenue'), ('TOM_MBOYA', 'Tom Mboya Street'), ('MAMA_NGINA', 'Mama Ngina Street'), ('KIMATHI', 'Kimathi Street'), ('STANDARD_ST', 'Standard Street'), ('BAZAAR_ST', 'Bazaar Street'), ('BIASHARA_ST', 'Biashara Street'), ('PARLIAMENT_RD', 'Parliament Road'), ('HARAMBEE_AVE', 'Harambee Avenue'), ('WABERA', 'Wabera Street'), ('CENTRAL_POLICE', 'Central Police Station Area'), ('PARLIAMENT_BUILDINGS', 'Parliament Buildings'), ('SUPREME_COURT', 'Supreme Court Area'), ('CITY_HALL', 'Nairobi City Hall'), ('NSE', 'Nairobi Securities Exchange'), ('KICC', 'Kenyatta International Convention Centre'), ('CENTRAL_BANK', 'Central Bank of Kenya'), ('KIAMBU', 'Kiambu Town'), ('RUIRU', 'Ruiru'), ('THIKA', 'Thika'), ('LIMURU', 'Limuru'), ('KIKUYU', 'Kikuyu'), ('GITHUNGURI', 'Githunguri'), ('MACHAKOS', 'Machakos Town'), ('ATHI_RIVER', 'Athi River (Mavoko)'), ('SYOKIMAU', 'Syokimau'), ('KATANI', 'Katani'), ('KITENGELA', 'Kitengela'), ('ONGATA_RONGAI', 'Ongata Rongai'), ('KISERIAN', 'Kiserian'), ('NGONG', 'Ngong')], default='KENCOM', help_text='Delivery destination', max_length=50),
        ),
    ]
