# Generated by Django 5.1.6 on 2025-03-06 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_category_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='category',
            name='updated_at',
        ),
    ]
