# Generated by Django 5.1.6 on 2025-03-06 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_category_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
