# Generated by Django 5.1.6 on 2025-03-01 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Transaction amount in KES', max_digits=10)),
                ('checkout_id', models.CharField(db_index=True, help_text='M-Pesa Checkout Request ID', max_length=100, unique=True)),
                ('mpesa_code', models.CharField(blank=True, db_index=True, help_text='M-Pesa Transaction Code', max_length=100, null=True, unique=True)),
                ('phone_number', models.CharField(db_index=True, help_text='Customer phone number', max_length=15)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Success', 'Success'), ('Failed', 'Failed')], db_index=True, default='Pending', help_text='Transaction status', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Transaction creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update timestamp')),
            ],
            options={
                'verbose_name': 'M-Pesa Transaction',
                'verbose_name_plural': 'M-Pesa Transactions',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['status', 'timestamp'], name='mpesaconfig_status_2a7065_idx'), models.Index(fields=['phone_number', 'status'], name='mpesaconfig_phone_n_4af0dd_idx')],
            },
        ),
    ]
